### ISSUE TITLE
Forward `RequestInfoInit` to `ResponseError`

### ISSUE THREAD

**Issue by valeriobelli** [contactlab/appy#743]
**Is your feature request related to a problem? Please describe.**

While developing a new combinator to log errors generated by `appy`, I realized that accessing the `RequestInfoInit` is impossible when handling a `ResponseError`. At the same time, the same is available in `RequestError`. Having the information about the Request is highly important when logging the failure to have a complete picture of what happened during the communication with the API.

**Describe the solution you'd like**

Extending the `ResponseError` by adding the `RequestInfoInit` as a property as done with `RequestError`. However, this will force the library to introduce a breaking change in `toResponseError` interface.

**Describe alternatives you've considered**

None.

**Additional information/context**

**Comment by StefanoMagrassi** [comment]
@valeriobelli thank you: this is a use case that the library should cover.

Even if the package is not widely used, I'm concerned about introducing a breaking change like this right now.

If you need this feature _a.s.a.p._ we can add an optional `input` field to the `ResponseError` interface in order to be retro-compatible.
Then, this field would be set as required in the next major version of the library.

The drawback would be that you will check in your code that the field is defined every time you will access to a `ResponseError` object.

**Comment by valeriobelli** [comment]
Ciao @StefanoMagrassi 👋🏽 
Thanks for the answer.

It's an excellent trade-off to avoid an immediate breaking change and let Appy's consumers adapt to the new interface.

**Comment by valeriobelli** [comment]
@StefanoMagrassi It tested against our test battery of some Appy's abstractions, and it worked like a charm. 

Having the `input` even for the Resp is an excellent addition to this library.

Thank you for the prompt effort. 💯
